[build]
base = "/"
publish = "/dist"
functions = "/nul"
command = "npm run build"

[dev]
port = 18888
targetPort = 28888
functionsPort = 38888
autoLaunch = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 308
force = false
