[build]
base = "."
publish = "./.next"
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[headers]]
for = "/*"

[headers.values]
Permissions-Policy = "geolocation=(self), camera=(), microphone=(), payment=()"
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
