[build]
base = "/"
publish = "/dist"
functions = "/faas"
command = "npm run bulid"

[dev]
port = 18888
targetPort = 28888
functionsPort = 38888
autoLaunch = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 308
force = true
